server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 2
  devtools:
    restart:
    additional-paths: src/main/java/com/yucheng/estm